# Generated by Django 4.1.4 on 2023-09-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drustvena_mrezaApp', '0003_alter_objava_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='objava',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('sports', 'Sports'), ('entertainment', 'Entertainment')], default='tech', max_length=20),
        ),
        migrations.AddField(
            model_name='objava',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='public', max_length=10),
        ),
    ]
