# Generated by Django 4.1.4 on 2023-09-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drustvena_mrezaApp', '0004_objava_category_objava_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', related_query_name='followers', to='drustvena_mrezaApp.profil'),
        ),
    ]
